import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Topbar from "@/components/Topbar";
import RightSidebar from "@/components/RightMenuComponent/RightSidebar";
import LeftSidebar from "@/components/LeftMenuComponent/LeftSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moowin Casino",
  description: "Generated by Next.js App Router",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#060b1f] text-white`}
      >
        {/* Contenedor Principal */}
        <div className="flex min-h-screen">
          {/* Left Sidebar - Oculto en Mobile */}
          <div className="hidden lg:block sticky top-0 h-screen w-64">
            <LeftSidebar />
          </div>

          {/* Main Content Area */}
          <div className="flex-1 overflow-auto bg-[#060b1f]">
            <Topbar />
            <main className="p-4 sm:p-6">{children}</main>
          </div>

          {/* Right Sidebar - Oculto en Mobile */}
          <div className="hidden lg:block sticky top-0 h-screen w-72">
            <RightSidebar />
          </div>
        </div>

        {/* Menú Lateral en Móvil */}
        <div className="lg:hidden fixed bottom-0 left-0 right-0 bg-[#0d1026] flex justify-around p-2 shadow-md">
          <button className="text-white flex items-center flex-col">
            <span>🏠</span>
            <span className="text-xs">Home</span>
          </button>
          <button className="text-white flex items-center flex-col">
            <span>🎲</span>
            <span className="text-xs">Games</span>
          </button>
          <button className="text-white flex items-center flex-col">
            <span>👤</span>
            <span className="text-xs">Profile</span>
          </button>
        </div>
      </body>
    </html>
  );
}
